services:
  mongo:
    image: mongo
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo-data:/data/db

  frontend:
    build:
      context: ./Frontend/message_app_project
      dockerfile: dockerfile
    ports:
      - "${FRONTEND_PORT}:5173"
    env_file:
      - .env
    environment:
      - VITE_API_URL=http://backend:${BACKEND_PORT}


  backend:
    build:
      context: ./Backend
      dockerfile: dockerfile
    depends_on:
      - mongo
    ports:
      - "${BACKEND_PORT}:3000"
    env_file:
      - .env
    environment:
      - MONGO_URL=${MONGO_URL}
      - PORT=${BACKEND_PORT}
      
volumes:
  mongo-data:
    driver: local