name: Auto Deployment Workflow

on:
  push:
    branches:
      [main, master]

  workflow_run:
    workflows: 
        ["backend_tests.yml", "frontend_tests.yml"]
    types:
      - completed

jobs:
  check-success:
    runs-on: ubuntu-latest
    steps:
      - name: Check if tests passed
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        run: echo "ðŸŽ‰ Success :)!"