name: Run Backend Tests

on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install
        working-directory: ./Backend

      - name: Run tests and save log
        run: |
          mkdir -p ./test_logs
          npm test -- --reporter=spec | tee ./test_logs/backend_test_log.txt
        working-directory: ./Backend
        env:
          CI: true

      - name: Upload test logs
        uses: actions/upload-artifact@v3
        with:
          name: backend-test-logs
          path: ./Backend/test_logs/backend_test_log.txt