name: Run Backend Tests

on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install
        working-directory: ./Backend

      - name: Run tests and save log
        # ensure that the report is output to the backend_test_log.txt, as well as in the actions console 
        run: |
          mkdir -p ./test_logs
          npx jest --reporters=default --silent=false 2>&1 | tee ./test_logs/backend_test_log.txt
        working-directory: ./Backend
        env:
          CI: true

      #Upload the test logs produced in actions to a github artifact
      - name: Upload test logs
        uses: actions/upload-artifact@v4
        with:
          name: backend-test-logs
          path: ./Backend/test_logs/backend_test_log.txt