name: Run Frontend Tests

on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install
        working-directory: ./Frontend/message_app_project
      
      #save the testing log in a folder on the frontend, to be uploaded as an artifact
      - name: Run tests and save log
        run: |
          mkdir -p ./test_logs
          npx vitest run --reporter verbose 2>&1 | tee ./test_logs/frontend_test_log.txt
        working-directory: ./Frontend/message_app_project
        env:
          CI: true

      #Upload the test logs produced in actions to a github artifact
      - name: Upload test logs
        uses: actions/upload-artifact@v4
        with:
          name: frontend-test-logs
          path: ./Frontend/message_app_project/test_logs/frontend_test_log.txt      