name: Run Frontend Tests

on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install
        working-directory: ./Frontend/message_app_project

      - name: Run tests
        run: npm test
        working-directory: ./Frontend/message_app_project
        env:
          CI: true